[unix_http_server]
file=/var/run/supervisor/supervisor.sock
chmod=0700

[supervisord]
pidfile=/var/log/supervisor/supervisord.log
logfile=/var/run/supervisor/supervisord.pid
childlogdir=/var/log/supervisor
nodaemon=true

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor/supervisor.sock

[program:backend]
directory=/usr/share/milimovideo
command=/bin/bash ./run_backend.sh
redirect_stderr=true
stdout_logfile=/usr/share/milimovideo/backend.log
startsecs = 0
autorestart = true
startretries = 3
user = milimo
group = milimo

[program:sam3]
directory=/usr/share/milimovideo
command=/bin/bash ./run_sam.sh
redirect_stderr=true
stdout_logfile=/usr/share/milimovideo/sam3.log
startsecs = 0
autorestart = true
startretries = 3
user = milimo
group = milimo

[program:frontend]
directory=/usr/share/milimovideo
command=/bin/bash ./run_frontend.sh
redirect_stderr=true
stdout_logfile=/usr/share/milimovideo/frontend.log
startsecs = 0
autorestart = true
startretries = 3
user = milimo
group = milimo
